permalink: /articles/:title/
encoding: utf-8
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "article"
url: http://rkuykendall.com
